### ISSUE TITLE
Rewasd doesnt work

### ISSUE THREAD

**Issue by Kadzia24** [RedDot-3ND7355/reWASD#3] opened 2023-12-11 15:04 UTC
The application starts normally, but after clicking start, nothing happens

**Comment by EugeneSunrise** [comment] 2023-12-17 14:26
> Scrapped the entire crack and started from scratch. Will have it ready soon! :) [as mentioned in other issues]

Bro, check tg and my repo

**Comment by RedDot-3ND7355** [comment] 2023-12-20 13:15
Re-Restarting from scratch with required changes for features and license to work! 
Closing this issue as it's a duplicate of #1

**Closed by RedDot-3ND7355** 2023-12-20 13:15 UTC
